matrix:
    include:
        - os: osx
          sudo: required
          osx_image: xcode11.3
          language: node_js
          node_js: '12'
          env:
                - ELECTRON_CACHE=$HOME/.cache/electron
                - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
                - TRAVIS_OS_NAME=macosx
                - GITHUB_TOKEN=d10414f80a2c6f26b471a4c7a2de6d18f8f578b0
                - GH_TOKEN=d10414f80a2c6f26b471a4c7a2de6d18f8f578b0
                - CI=false

        - os: linux
          sudo: required
          services: 
            - docker
          language: node_js
          node_js: '12'
          env:
                - ELECTRON_CACHE=$HOME/.cache/electron
                - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
                - TRAVIS_OS_NAME=linux
                - GH_TOKEN=d10414f80a2c6f26b471a4c7a2de6d18f8f578b0
                - GITHUB_TOKEN=d10414f80a2c6f26b471a4c7a2de6d18f8f578b0
                - CI=false
compiler:
    - gcc
    - clang

cache:
    directories:
        - assets
        - node_modules
        - $HOME/.cache/electron
        - $HOME/.cache/electron-builder

script:
    - npm install
    - npm run build
    - |
        if [ "$TRAVIS_OS_NAME" == "macosx" ]; then
            npm run mac-release
        else
          npm run mac-release 
        fi
    - |
        if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            docker run --rm \
                --env ELECTRON_CACHE="/root/.cache/electron" \
                --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
                -v ${PWD}:/project \
                -v ~/.cache/electron:/root/.cache/electron \
                -v ~/.cache/electron-builder:/root/.cache/electron-builder \
                electronuserland/builder \
                /bin/bash -c "npm run linux-release"
            docker run --rm \
                --env ELECTRON_CACHE="/root/.cache/electron" \
                --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
                -v ${PWD}:/project \
                -v ~/.cache/electron:/root/.cache/electron \
                -v ~/.cache/electron-builder:/root/.cache/electron-builder \
                electronuserland/builder:wine \
                /bin/bash -c "npm run win-release"
        else
          npm run linux-release 
        fi

before_cache:
    - rm -rf $HOME/.cache/electron-builder/wine

notifications:
  email:
    - lahiri.devs@gmail.com

branches:
    except:
        - "/^v\\d+\\.\\d+\\.\\d+$/"
