matrix:
    include:
        - os: osx
          sudo: required
          osx_image: xcode11.3
          language: node_js
          node_js: '12'
          env:
              - ELECTRON_CACHE=$HOME/.cache/electron
              - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
              - TRAVIS_OS_NAME=macosx
              - GITHUB_TOKEN=d10414f80a2c6f26b471a4c7a2de6d18f8f578b0
              - GH_TOKEN=d10414f80a2c6f26b471a4c7a2de6d18f8f578b0
              - CI=false

        # - os: linux
        #   sudo: required # for docker. 
        #   services: 
        #     - docker
        #   language: node_js
        #   node_js: '12'
        #   env:
        #       - ELECTRON_CACHE=$HOME/.cache/electron
        #       - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        #       - TRAVIS_OS_NAME=linux
        #       - GH_TOKEN=d10414f80a2c6f26b471a4c7a2de6d18f8f578b0
        #       - GITHUB_TOKEN=d10414f80a2c6f26b471a4c7a2de6d18f8f578b0
        #       - CI=false

cache:
    directories:
        - assets
        - node_modules
        - $HOME/.cache/electron
        - $HOME/.cache/electron-builder

# Update this later. 
script:
    - npm install
    - npm run build
    - |
        if [ "$TRAVIS_OS_NAME" == "macosx" ]; then
            npm run mac-release
        else
          npm run mac-release 
        fi
before_cache:
    - rm -rf $HOME/.cache/electron-builder/wine

branches:
    except:
        - "/^v\\d+\\.\\d+\\.\\d+$/"
