export const state = {
    change : {}, 
    signedIn : false,
    loggedIn : false, 
    addingTeam : false,
    loginStarted : false,
    loadingHome : true,
    loadingMembers : true,
    userProfileData : {},
    teamDataInfo : {},
    activeTeamId : 0, 
    memberList : {},
    activeMemberId : '',
    loggedInUserId : '',
  }